name: actions

on:
  push:
    branches: [ "feature_4" ]

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4
    - name: Copy .env.
      run: |
        echo "cp .env"
        cp cours4/td_backend/.env.ci .env
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: composer run test
      continue-on-error: false
    - name: Execute linter phpstan
      run: composer run phpstan
      continue-on-error: false
